### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by felbinger** [fu-sen/CloudflarePages-MkDocs#1]
Hello,

I tried to get it working (for the repo: https://github.com/secshellnet/docs) the last few days, unfortunately I get this error message:
```
<snip>
...
12:54:08.468 | Executing user command: mkdocs build
12:54:09.160 | INFO    -  Cleaning site directory
12:54:09.160 | INFO    -  Building documentation to directory: /opt/buildhome/repo/site
12:54:09.270 | ERROR   -  Error reading page 'index.de.md': list index out of range
12:54:09.273 | Traceback (most recent call last):
12:54:09.273 | File "/opt/buildhome/python3.7/bin/mkdocs", line 8, in &lt;module&gt;
12:54:09.273 | sys.exit(cli())
12:54:09.273 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
12:54:09.273 | return self.main(*args, **kwargs)
12:54:09.273 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1062, in main
12:54:09.273 | rv = self.invoke(ctx)
12:54:09.273 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
12:54:09.273 | return _process_result(sub_ctx.command.invoke(sub_ctx))
12:54:09.274 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
12:54:09.274 | return ctx.invoke(self.callback, **ctx.params)
12:54:09.274 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 763, in invoke
12:54:09.274 | return __callback(*args, **kwargs)
12:54:09.274 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 152, in build_command
12:54:09.274 | build.build(config.load_config(**kwargs), dirty=not clean)
12:54:09.274 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 271, in build
12:54:09.274 | _populate_page(file.page, config, files, dirty)
12:54:09.274 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 168, in _populate_page
12:54:09.274 | 'page_markdown', page.markdown, page=page, config=config, files=files
12:54:09.275 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
12:54:09.275 | result = method(item, **kwargs)
12:54:09.275 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/plugin.py", line 155, in on_page_markdown
12:54:09.275 | is_first_commit=False,
12:54:09.275 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/util.py", line 106, in get_git_commit_timestamp
12:54:09.275 | git = self._get_repo(realpath)
12:54:09.275 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/util.py", line 43, in _get_repo
12:54:09.275 | raise_ci_warnings(self.repo_cache[path])
12:54:09.275 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/ci.py", line 21, in raise_ci_warnings
12:54:09.275 | n_commits = commit_count(repo)
12:54:09.276 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/ci.py", line 88, in commit_count
12:54:09.276 | refs = [x.split()[0] for x in refs]
12:54:09.276 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/ci.py", line 88, in &lt;listcomp&gt;
12:54:09.276 | refs = [x.split()[0] for x in refs]
12:54:09.276 | IndexError: list index out of range
12:54:09.356 | Failed: build command exited with code: 1
```

![image](https://user-images.githubusercontent.com/26925347/120889479-b3456780-c5fd-11eb-9853-a4a54a32733e.png)

Did anyone else experience this error before?
If I try to build it locally using `mkdocs build` it works as expected:
```
$ mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/felbinger/projects/secshellnet-docs/site 
INFO    -  Documentation built in 0.40 seconds 
```

**Comment by fu-sen** [comment]
I tried your repository on my PC.
It's so complicated that it looks like the contents of `mkdocs.yml` and `docs/ `do not match.
Check the details with the preview command of mkdocs: `mkdocs serve`

When I minimized `mkdocs.yml`, the output is done:
```
site_name: Secure Shell Networks
```

Also, there is `index.de.md` etc. in` docs/ `,
which is not the standard MkDocs file structure. Or the plugin may still be missing.

This is a MkDocs level error, so if you want help, please visit MkDocs GitHub discussions:
https://github.com/mkdocs/mkdocs/discussions

This is not a `CloudflarePages-MkDocs` error.
Also, this project uses a plugin that I don't understand,
so I can't take any further action. sorry. Close this issue.
